[project]
name        = 'rx_pid'
version     = '0.0.1'
readme      = 'README.md'
dependencies= [
'pidcalib2']

[project.optional-dependencies]
dev  = ['pytest']

[tools.setuptools.packages.find]
where   = ['src']

[project.scripts]
create_pidcalib2_histograms_scripts='rx_pid.create_pidcalib2_histograms_scripts:main'
plot_histograms='rx_pid.plot_histograms:main'

[tool.setuptools.package-data]
rx_pid_data=['*/*.json', '*/*.yaml', '*/*.submit']

[tool.setuptools]
script-files=['src/rx_pid_scripts/make_maps']
