# This file is used to measure PIDe efficiencies for pions, kaons and electrons
# falling outside the signal region, but within [1,3] in PIDe

samples  :
  2024: 2024
  b1  : 2024_WithUT_block1_v1
  b2  : 2024_WithUT_block2
  b3  : 2024_WithUT_block3
  b5  : 2024_WithUT_block5
  b6  : 2024_WithUT_block6
  b7  : 2024_WithUT_block7
  b8  : 2024_WithUT_block8
cuts  :
  - PARTICLE_TRACK_GHOSTPROB < 0.3
  - PARTICLE_PT              > 250
  - PARTICLE_P               > 3000
  - PARTICLE_IPCHI2          > 9
  - PARTICLE_PROBNN_E        > 0.2
  - PARTICLE_PPHASRICH
common: &com
  bin_vars :
    - P
    - ETA
particles:
  Pi  :
    <<: *com
    pid_cuts       :
      - pi_PID_E < 3.0
      - pi_PID_E > 1.0
  K   :
    <<: *com
    pid_cuts       :
      - K_PID_E < 3.0
      - K_PID_E > 1.0
