# This file is used to measure PIDe efficiencies for pions, kaons and electrons
# falling outside the signal region, but within [1,3] in PIDe
#
#
# -----------------------------------------------
samples_ee:
  b10 : 2024_WithUT_block1_Tables_1brem_tag
  b11 : 2024_WithUT_block1_Tables_2brem
  # --------
  b50 : 2024_WithUT_block5_Tables_1brem_tag
  b51 : 2024_WithUT_block5_Tables_2brem
  # --------
  b70 : 2024_WithUT_block7_Tables_1brem_tag
  b71 : 2024_WithUT_block7_Tables_2brem
selection_ee:
  - PT              > 250
  - P               > 3000
  - IPCHI2          > 9
  - PROBNN_E        > 0.2
  - PARTICLE_PPHASRICH
# -----------------------------------------------
samples  :
  b1  : 2024_WithUT_block1_v1
  b2  : 2024_WithUT_block2
  b3  : 2024_WithUT_block3
  b5  : 2024_WithUT_block5
  b6  : 2024_WithUT_block6
  b7  : 2024_WithUT_block7
  b8  : 2024_WithUT_block8
selection :
  - TRACK_GHOSTPROB < 0.3
  - PT              > 250
  - P               > 3000
  - IPCHI2          > 9
  - PROBNN_E        > 0.2
  - PARTICLE_PPHASRICH
# -----------------------------------------------
common: &com
  bin_vars :
    - P
    - ETA
  pid_cuts:
    - (DLLe > 1.0) & (DLLe < 3.0) #Control region
    - DLLe > 3.0                  #Signal region
particles:
  e   :
    <<: *com
  Pi  :
    <<: *com
  K   :
    <<: *com
