samples  :
  2024: 2024
  b1  : 2024_WithUT_block1_v1
  b2  : 2024_WithUT_block2
  b3  : 2024_WithUT_block3
  b5  : 2024_WithUT_block5
  b6  : 2024_WithUT_block6
  b7  : 2024_WithUT_block7
  b8  : 2024_WithUT_block8
common: &com
  bin_vars :
    - P
    - ETA
particles:
  Mu :
    <<: *com
    channel        : JpsiToMuMu
    pid_cuts       :
      - IsMuon == 1
      - muprobe_PID_MU > -4
  Pi  :
    <<: *com
    channel        : DstToD0Pi_D0ToKPi
    pid_cuts       :
      - pi_PID_K < 0.00001
  K   :
    <<: *com
    channel        : DstToD0Pi_D0ToKPi
    pid_cuts       :
      - K_PID_K > -5
