# This file is used to measure PIDe efficiencies for pions, kaons and electrons
# falling outside the signal region, but within [1,3] in PIDe

samples  :
  2024: 2024
  b1  : 2024_WithUT_block1_v1
  b2  : 2024_WithUT_block2
  b3  : 2024_WithUT_block3
  b5  : 2024_WithUT_block5
  b6  : 2024_WithUT_block6
  b7  : 2024_WithUT_block7
  b8  : 2024_WithUT_block8
selection :
  - TRACK_GHOSTPROB < 0.3
  - PT              > 250
  - P               > 3000
  - IPCHI2          > 9
  - PROBNN_E        > 0.2
  - PARTICLE_PPHASRICH
common: &com
  bin_vars :
    - P
    - ETA
particles:
  Pi  :
    <<: *com
    pid_cuts       :
      - DLLe < 3.0
      - DLLe > 1.0
  K   :
    <<: *com
    pid_cuts       :
      - DLLe < 3.0
      - DLLe > 1.0
