# This file is used to measure PIDe efficiencies for pions, kaons and electrons
# in the control region for Analysis samples, with PIDe in [1,inf]
#
# -----------------------------------------------
samples_ee:
  b10 : 2024_WithUT_block1_Tables_1brem_tag
  b11 : 2024_WithUT_block1_Tables_2brem
  # --------
  b50 : 2024_WithUT_block5_Tables_1brem_tag
  b51 : 2024_WithUT_block5_Tables_2brem
  # --------
  b70 : 2024_WithUT_block7_Tables_1brem_tag
  b71 : 2024_WithUT_block7_Tables_2brem
selection_ee:
  - PT              > 250
  - P               > 3000
# -----------------------------------------------
samples  :
  b1  : 2024_WithUT_block1_v1
  b2  : 2024_WithUT_block2
  b3  : 2024_WithUT_block3
  b5  : 2024_WithUT_block5
  b6  : 2024_WithUT_block6
  b7  : 2024_WithUT_block7
  b8  : 2024_WithUT_block8
selection :
  - TRACK_GHOSTPROB < 0.3
  - PT              > 250
  - P               > 3000
  - IPCHI2          > 9
  - PARTICLE_PPHASRICH
  - PARTICLE_INECAL
# -----------------------------------------------
common: &com
  bin_vars :
    - P
    - ETA
particles:
  Pi  :
    <<: *com
    pid_cuts:
      - PROBNN_E < 0.2 | DLLe < 3
      - DLLe     > 1.0
      - PROBNN_K < 0.1
  K   :
    <<: *com
    pid_cuts:
      - PROBNN_E < 0.2 | DLLe < 3
      - DLLe     > 1.0
      - PROBNN_K > 0.1
